# Generated by Django 5.2.8 on 2025-12-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desk",
            name="id_card",
        ),
        migrations.AddField(
            model_name="desk",
            name="id_card_url",
            field=models.URLField(
                blank=True,
                help_text="Private Cloudinary URL for uploaded ID document",
                null=True,
            ),
        ),
    ]
