# Generated by Django 5.2.8 on 2025-12-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_desk_id_card_desk_id_card_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="desk",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
