# Generated by Django 5.2.8 on 2025-12-22 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trades", "0004_alter_trade_desk_alter_asset_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "desk_name",
                    models.CharField(
                        help_text="Snapshot of desk name at invoice time",
                        max_length=255,
                    ),
                ),
                ("asset_symbol", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("pdf_url", models.URLField(blank=True)),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trade",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="trades.trade",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
    ]
