# Generated by Django 5.2.8 on 2025-12-21 01:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Asset symbol (e.g. BTC, ETH, USDT)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable asset name", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive assets remain for historical records",
                    ),
                ),
                (
                    "is_custom",
                    models.BooleanField(
                        default=False,
                        help_text="True if asset was user-added (OTC / obscure asset)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Desk name (e.g. OTC Desk, P2P Desk)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Desk",
                "verbose_name_plural": "Desks",
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
                (
                    "amount_crypto",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Crypto amount traded",
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
                (
                    "amount_ngn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual cash value of the trade (NGN)",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Reference rate (NGN per 1 unit of crypto)",
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Auto-calculated realized P&L (NGN)",
                        max_digits=18,
                    ),
                ),
                (
                    "trade_date",
                    models.DateTimeField(help_text="When the trade actually occurred"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trades",
                        to="trades.asset",
                    ),
                ),
                (
                    "desk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trades",
                        to="trades.desk",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade",
                "verbose_name_plural": "Trades",
                "ordering": ["-trade_date"],
                "indexes": [
                    models.Index(
                        fields=["trader", "trade_date"],
                        name="trades_trad_trader__951131_idx",
                    ),
                    models.Index(
                        fields=["asset", "trade_date"],
                        name="trades_trad_asset_i_cf3856_idx",
                    ),
                    models.Index(
                        fields=["desk", "trade_date"],
                        name="trades_trad_desk_id_45dfa4_idx",
                    ),
                ],
            },
        ),
    ]
