# Generated by Django 5.2.8 on 2025-12-21 02:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[
                    ("spot", "Spot"),
                    ("otc", "OTC"),
                    ("p2p", "P2P"),
                    ("futures", "Futures"),
                ],
                default="spot",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive assets remain usable for history"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="is_custom",
            field=models.BooleanField(
                default=False, help_text="True if asset was user-added"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="desk",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="amount_crypto",
            field=models.DecimalField(
                decimal_places=8,
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("1E-8"))],
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="amount_ngn",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Actual cash value of the trade",
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="desk",
            field=models.ForeignKey(
                help_text="Desk derived from trader account",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trades",
                to="trades.desk",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="profit_loss",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                help_text="Auto-calculated realized P&L",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Reference rate (NGN per unit)",
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trader",
            field=models.ForeignKey(
                help_text="User who recorded the trade",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["trade_type"], name="trades_trad_trade_t_410362_idx"
            ),
        ),
    ]
