# Generated by Django 5.2.8 on 2025-12-21 02:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0002_trade_trade_type_alter_asset_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Inactive assets remain for historical accuracy"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="is_custom",
            field=models.BooleanField(
                default=True, help_text="True if asset was auto-created by user input"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(
                blank=True, help_text="Optional descriptive name", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.CharField(
                help_text="Asset symbol (e.g. BTC, USDT, ETH)",
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="amount_ngn",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="desk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trades",
                to="trades.desk",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="profit_loss",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=18),
        ),
        migrations.AlterField(
            model_name="trade",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                help_text="NGN per unit",
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
