# Generated by Django 5.2.8 on 2025-12-21 02:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0003_alter_asset_is_active_alter_asset_is_custom_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="desk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trades",
                to="users.desk",
            ),
        ),
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["symbol"]},
        ),
        migrations.AlterModelOptions(
            name="trade",
            options={"ordering": ["-trade_date"]},
        ),
        migrations.RemoveIndex(
            model_name="trade",
            name="trades_trad_trader__951131_idx",
        ),
        migrations.RemoveIndex(
            model_name="trade",
            name="trades_trad_asset_i_cf3856_idx",
        ),
        migrations.RemoveIndex(
            model_name="trade",
            name="trades_trad_desk_id_45dfa4_idx",
        ),
        migrations.RemoveIndex(
            model_name="trade",
            name="trades_trad_trade_t_410362_idx",
        ),
        migrations.AlterField(
            model_name="asset",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="is_custom",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="rate",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="trade",
            name="trade_type",
            field=models.CharField(
                choices=[
                    ("spot", "Spot"),
                    ("otc", "OTC"),
                    ("p2p", "P2P"),
                    ("futures", "Futures"),
                ],
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Desk",
        ),
    ]
