# Generated by Django 5.2.8 on 2025-12-25 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisory", "0002_alter_tradeinsight_options_riskreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreport",
            name="ai_summary",
            field=models.TextField(
                blank=True, help_text="AI-generated text used in the report"
            ),
        ),
        migrations.AlterField(
            model_name="riskreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="riskreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="riskreport",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="advisory_ri_user_id_0aafbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskscore",
            index=models.Index(
                fields=["user", "-created_at"], name="advisory_ri_user_id_6efb8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradeinsight",
            index=models.Index(
                fields=["user", "-created_at"], name="advisory_tr_user_id_7a54c3_idx"
            ),
        ),
    ]
