# Generated by Django 5.2.8 on 2025-12-24 00:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="badge",
            name="min_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="badge",
            name="min_trades",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="ophistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("trade_logged", "Trade Logged"),
                    ("trade_bonus", "Fast Trade Bonus"),
                    ("invite", "Invite Teammate"),
                    ("badge_unlocked", "Badge Unlocked"),
                    ("system", "System Award"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="gamificatio_user_id_7cbbbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ophistory",
            index=models.Index(fields=["user"], name="gamificatio_user_id_404d1e_idx"),
        ),
        migrations.AddIndex(
            model_name="ophistory",
            index=models.Index(fields=["action"], name="gamificatio_action_ae50ae_idx"),
        ),
        migrations.AddIndex(
            model_name="ophistory",
            index=models.Index(
                fields=["created_at"], name="gamificatio_created_5a2b2a_idx"
            ),
        ),
    ]
